name: Prebuild devcontainer image

on:
  push:
    branches: [main]
    paths: ['.devcontainer/**']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push devcontainer image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/kittipitch/cs111-devcontainer
          cacheFrom: ghcr.io/kittipitch/cs111-devcontainer
          push: always
